import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import { createPinia } from 'pinia';
import { setupQiankun } from './micro-frontend/registry';
import naive from 'naive-ui';
import { setupPermission } from './composables/usePermission';
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.use(naive);
setupPermission(app);
setupQiankun(router);
app.mount('#app');
