#!/bin/sh
set -eu
CORE_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
export CORE_ROOT
. "$CORE_ROOT/sbin/lib/common.sh"
. "$CORE_ROOT/sbin/lib/audit.sh"
. "$CORE_ROOT/sbin/lib/key_store.sh"
. "$CORE_ROOT/sbin/lib/pki_common.sh"
. "$CORE_ROOT/sbin/lib/pki_ext.sh"
OP=""; IN=""; OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --op)  OP="$2";  shift 2 ;;
    --in)  IN="$2";  shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    *)     pki_fail "$OUT" "INVALID_PARAM" "unknown argument: $1" '{}' 2 ;;
  esac
done
[ -n "$OP" ] && [ -n "$IN" ] && [ -n "$OUT" ] || pki_fail "$OUT" "INVALID_PARAM" "missing args" '{}' 2
[ -f "$IN" ] || pki_fail "$OUT" "INVALID_PARAM" "input json not found" '{}' 2
pki_require_jq
START=$(date +%s)
REQ="$(json_get "$IN" '.request_id')"
TASK="$(json_get_def "$IN" '.task_id' '')"
SERVER="$(json_get "$IN" '.params.server_type')"
CERT="$(json_get "$IN" '.params.cert_path')"
KEY_REF="$(json_get "$IN" '.params.key_ref')"
OUT_PATH="$(json_get_def "$IN" '.params.output_path' '')"
case "$SERVER" in nginx|tengine|angie) ;; *) pki_fail "$OUT" "INVALID_PARAM" "invalid server_type" '{}' 2 ;; esac
pki_require_param "$IN" '.params.server_type' 'server_type' "$OUT" 2
pki_require_param "$IN" '.params.cert_path' 'cert_path' "$OUT" 2
pki_require_param "$IN" '.params.key_ref' 'key_ref' "$OUT" 2
if [ -z "$OUT_PATH" ]; then
  OUT_PATH="data/ssl/${SERVER}-$(pki_new_id ssl).conf"
fi
ABS_OUT="$(pki_ext_require_under_core "$OUT_PATH" "output_path" "$OUT")"
pki_mkdir_for "$ABS_OUT"
cat > "$ABS_OUT" <<EOF
# generated by Tongsuo core, do not edit by hand
ssl_certificate $CERT;
ssl_certificate_key key_ref:$KEY_REF;
ssl_protocols TLSv1.3 TLSv1.2;
ssl_ciphers HIGH:!aNULL:!MD5;
EOF
chmod 0644 "$ABS_OUT" 2>/dev/null || true
DUR=$(( $(date +%s) - START ))
pki_write_audit "$REQ" "$TASK" "$OP" "" "SUCCESS" "$DUR" "" "$IN"
DATA="$(jq -n --arg path "$OUT_PATH" --arg server "$SERVER" '{config_path:$path,server_type:$server}')"
AUDIT="$(jq -n --arg audit_id "audit-$(date +%s)-$$" --arg params_digest "$(pki_calc_params_digest "$IN")" --argjson duration_ms "$DUR" \
  '{audit_id:$audit_id,params_digest:$params_digest,result:"SUCCESS",duration_ms:$duration_ms}')"
pki_success "$IN" "$OUT" "$OP" "$REQ" "$TASK" "$DATA" "$AUDIT"
exit 0
