package handler

import (
    "context"
    "fmt"
    "os"
    "path/filepath"
    "time"

    "github.com/yourorg/core-go/internal/audit"
    "github.com/yourorg/core-go/internal/config"
    "github.com/yourorg/core-go/internal/envelope"
    "github.com/yourorg/core-go/internal/pathguard"
)

// SSLConfigGenerateHandler ssl.config.generate。
type SSLConfigGenerateHandler struct{}

func (h *SSLConfigGenerateHandler) Execute(
    ctx context.Context, req *envelope.Request, cfg *config.Config,
) *envelope.Response {
    start := time.Now()

    serverType := strParam(req.Params, "server_type")
    switch serverType {
    case "nginx", "tengine", "angie":
    default:
        return genErr("INVALID_PARAM", "invalid server_type")
    }

    certRel := strParam(req.Params, "cert_path")
    keyRef := strParam(req.Params, "key_ref")
    if certRel == "" || keyRef == "" {
        return genErr("INVALID_PARAM", "missing cert_path or key_ref")
    }

    outRel := strParamDefault(req.Params, "output_path",
        "data/ssl/"+serverType+"-"+newID("ssl")+".conf")
    outAbs, err := pathguard.Resolve(outRel)
    if err != nil {
        return genErr("PATH_NOT_ALLOWED", err.Error())
    }
    if err := pathguard.EnsureDir(filepath.Dir(outAbs), 0750); err != nil {
        return genErr("CORE_EXEC_FAILED", err.Error())
    }

    content := fmt.Sprintf(
        "# generated by core-go, do not edit\n"+
            "ssl_certificate %s;\n"+
            "ssl_certificate_key key_ref:%s;\n"+
            "ssl_protocols TLSv1.3 TLSv1.2;\n"+
            "ssl_ciphers HIGH:!aNULL:!MD5;\n",
        certRel, keyRef)
    if err := os.WriteFile(outAbs, []byte(content), 0644); err != nil {
        return genErr("CORE_EXEC_FAILED", err.Error())
    }

    audit.Log(req, "ssl.config.generate", start, "SUCCESS", "")
    return envelope.NewSuccess(map[string]interface{}{
        "config_path": outRel,
        "server_type": serverType,
    })
}
