"""init

Revision ID: 041c6783a402
Revises: 
Create Date: 2026-09-10 10:36:15.583885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041c6783a402'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_permission_code'), 'auth_permission', ['code'], unique=True)
    op.create_index(op.f('ix_auth_permission_id'), 'auth_permission', ['id'], unique=False)
    op.create_index(op.f('ix_auth_permission_module_id'), 'auth_permission', ['module_id'], unique=False)
    op.create_table('auth_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.SmallInteger(), nullable=False, comment='1-系统内置'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_role_code'), 'auth_role', ['code'], unique=True)
    op.create_index(op.f('ix_auth_role_id'), 'auth_role', ['id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1-启用 0-禁用'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_email'), 'auth_user', ['email'], unique=False)
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('sys_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False, comment='配置键'),
    sa.Column('value', sa.String(length=512), nullable=False, comment='配置值'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_config_id'), 'sys_config', ['id'], unique=False)
    op.create_index(op.f('ix_sys_config_key'), 'sys_config', ['key'], unique=True)
    op.create_table('auth_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.SmallInteger(), nullable=False, comment='1-已撤销 0-有效'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_refresh_token_expires_at'), 'auth_refresh_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_token_id'), 'auth_refresh_token', ['id'], unique=False)
    op.create_index(op.f('ix_auth_refresh_token_token_hash'), 'auth_refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_refresh_token_user_id'), 'auth_refresh_token', ['user_id'], unique=False)
    op.create_table('auth_role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_auth_role_permission_role_perm')
    )
    op.create_index(op.f('ix_auth_role_permission_id'), 'auth_role_permission', ['id'], unique=False)
    op.create_table('auth_user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_auth_user_role_user_role')
    )
    op.create_index(op.f('ix_auth_user_role_id'), 'auth_user_role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_role_id'), table_name='auth_user_role')
    op.drop_table('auth_user_role')
    op.drop_index(op.f('ix_auth_role_permission_id'), table_name='auth_role_permission')
    op.drop_table('auth_role_permission')
    op.drop_index(op.f('ix_auth_refresh_token_user_id'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_token_hash'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_id'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_expires_at'), table_name='auth_refresh_token')
    op.drop_table('auth_refresh_token')
    op.drop_index(op.f('ix_sys_config_key'), table_name='sys_config')
    op.drop_index(op.f('ix_sys_config_id'), table_name='sys_config')
    op.drop_table('sys_config')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_email'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index(op.f('ix_auth_role_id'), table_name='auth_role')
    op.drop_index(op.f('ix_auth_role_code'), table_name='auth_role')
    op.drop_table('auth_role')
    op.drop_index(op.f('ix_auth_permission_module_id'), table_name='auth_permission')
    op.drop_index(op.f('ix_auth_permission_id'), table_name='auth_permission')
    op.drop_index(op.f('ix_auth_permission_code'), table_name='auth_permission')
    op.drop_table('auth_permission')
    # ### end Alembic commands ###
